### ISSUE TITLE
Add support for AWS "OpenSearch"?

### ISSUE THREAD

**Issue by TonyLovesDevOps** [phillbaker/terraform-provider-elasticsearch#218]
AWS has [officially renamed AWS Elasticsearch to OpenSearch](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html) after forking Elasticsearch to OpenSearch and Kibana to OpenSearch Dashboards at [opensearch.org](https://opensearch.org), because lawyers and 💰.

There are at least two immediate issues with this provider supporting OpenSearch:

1. OpenSearch returns `version.number: "1.0.0"` from the default endpoint even though it's really ES `7.10.2` under the hood so the provider returns `Error: ElasticSearch is older than 5.0.0!` when trying to apply changes. This can be worked around by [enabling compatibility mode](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html#rename-upgrade) so the domain returns `7.10` as its version;
2. I'm still looking into why, but when pointing the provider at an AWS OpenSearch domain (even with compatibility mode enabled) it returns several `Error: no URLs found: no Elasticsearch node available` during a plan operation.

Here's a repro for the first problem:

```yml
# docker-compose.yml
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:1.0.1
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.0.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```

```hcl
# opensearch_test.tf
terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "~> 1.6.3"
    }
  }
}

provider "elasticsearch" {
  insecure  = true # to bypass certificate check
  url       = "https://localhost:9200"
  username  = "admin"
  password  = "admin"
}

resource "elasticsearch_index" "foo" {
  name                = "foo"
  number_of_shards    = 1
  number_of_replicas  = 1
}
```

1. Save the docker-compose.yaml and terraform_object_test.tf files to a temp directory.
2. Run terraform init to set up the providers
3. Run docker compose up to set up the ES/kibana containers
4. Run terraform plan -out plan.out and terraform apply plan.out to create the index.

_Expected Behavior_
Successful apply.

_Actual Behavior_
`Error: ElasticSearch is older than 5.0.0!` returned.
